### ISSUE TITLE
Error al correr carwash.py en la GUI

### ISSUE THREAD

**Issue by M4nu0113** [SPAAutosMotos/MOTOR-SPA#1]
Traceback (most recent call last):
  File "c:\proyecto estructuras\carwash.py", line 279, in <module>
    my_app = Login()
             ^^^^^^^
  File "c:\proyecto estructuras\carwash.py", line 115, in __init__
    self.vt_configuracion.setting_eliminarpromocion.clicked.connect(self.abrir_eliminarDescuento)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Login' object has no attribute 'abrir_eliminarDescuento'. Did you mean: 'vt_eliminarDescuento'?

![Captura de pantalla 2024-05-30 155158](https://github.com/SPAAutosMotos/MOTOR-SPA/assets/138742359/d4ad0218-2c3f-4c18-ba67-e34cae9d79e2)

**Comment by SantiagoL-A2** [comment]
ya resuelto
